### ISSUE TITLE
Using stuff like lava buckets makes the buckets disappear

### ISSUE THREAD

**Issue by TheBlackEntity** [Gitko01/BlockActivators#1]
I just noticed while building a farm for the Create Blaze Burners that when using a lava bucket, the entire bucket disappears.

I don't think this is intended, is it?

**Comment by Gitko01** [comment]
Most definitely not, I'll see what I can do.

**Comment by TheBlackEntity** [comment]
> Most definitely not, I'll see what I can do.

I looked at the code and made a fix.

Mind if I make a request?
